name: Debug with tmate

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    timeout-minutes: 9999
    steps:
      - uses: actions/checkout@v4

      - name: Start tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true

      - name: Show WebURL
        if: always()
        run: |
          echo "👉 WebURL:"
          tmate -S /tmp/tmate.sock display -p '#{tmate_web}'
