name: Debug with tmate Web

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Install tmate
        run: |
          sudo apt-get update
          sudo apt-get install -y tmate

      - name: Start tmate
        run: |
          tmate -S /tmp/tmate.sock new-session -d
          tmate -S /tmp/tmate.sock wait tmate-ready
          echo "👉 SSH 地址:"
          tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}'
          echo "👉 WebURL:"
          tmate -S /tmp/tmate.sock display -p '#{tmate_web}'
          # 心跳打印，防止 GitHub 以为任务卡死
          while true; do
            echo "tmate session running..."
            sleep 60
          done

